### ISSUE TITLE
Exception: String reference not set to an instance of a String

### ISSUE THREAD

**Issue by yodasad** [DuendeArchive/IdentityModel.OidcClient.Old#14]
Hello!

It seems that there is a problem in the authorization code flow processing.

The exception occurs when trying to validate a token endpoint response.
It comes from `Encoding.UTF8.GetBytes(accessToken)` in the `ValidateAccessTokenHash` method.
The value of the `accessToken` variable is `null` because it comes from `authorizeResponse.AccessToken` which is `null` in the authorization code flow.
I think the code in the `ValidateCodeFlowResponse` method should be
`if (!ValidateAccessTokenHash(tokenResponse.AccessToken, validationResult.Claims))`
`{`
`result.Error = "invalid access token hash";`
`return result;`
`}`

There is another problem.
`Encoding.UTF8.GetBytes(accessToken)` should be replaced with `Encoding.ASCII.GetBytes(accessToken)` according to the OIDC spec:

> OPTIONAL. Access Token hash value. Its value is the base64url encoding of the left-most half of the hash of the octets of the ASCII representation of the access_token value

Correct me if I'm wrong.

Thank you!

**Comment by luisgoncalves** [comment]
The first problem is also the subject of #13.

**Comment by leastprivilege** [comment]
done and pushed. thanks!
