### ISSUE TITLE
Define GetHandler on LoginResult as extension method

### ISSUE THREAD

**Issue by xperiandri** [DuendeArchive/IdentityModel.OidcClient.Old#15]
Define GetHandler on LoginResult as extension method:
So that `Windows.Web.Http.HttpClient` can be used as well as using `System.Net.Http.HttpClient`.

Hence if I use `Windows.Web.Http` namespace the WinRT version will be used and if I use `System.Net.Http` namespace then .NET version will be used.

**Comment by leastprivilege** [comment]
PR?

**Comment by xperiandri** [comment]
Will do sometime later
