### ISSUE TITLE
LogoutAsync results in NullReferenceException

### ISSUE THREAD

**Issue by rdavisunr** [DuendeArchive/IdentityModel.OidcClient.Old#20]
The `LogoutAsync` method surfaces a NullReferenceException if the Manual interaction process is followed (`PrepareLoginAsync` followed by `ValidateResponseAsync`). This is because the AuthorizeClient's `EndSessionAsync` uses the WebView that could have optionally been passed to `OidcClientOptions`. 

The `LoginAsync`method throws an InvalidOperationException when no WebView is present; perhaps `LogoutAsync`should have the same behavior?

In any case, how can Logout be achieved when the Manual interaction process is followed?

**Comment by leastprivilege** [comment]
Logout is still a todo. But for now you are right - I should check for a web view impl and throw appropriately.

**Comment by leastprivilege** [comment]
added an InvalidOperationException for now. Until we have a better solution.
