### ISSUE TITLE
Should LoginResult.IdentityToken be set with TokenResponse.IdentityToken?

### ISSUE THREAD

**Issue by andrew-laughlin** [DuendeArchive/IdentityModel.OidcClient.Old#22]
Currently in the `ProcessClaims`method, `LoginResult.IdentityToken` is set using `AuthorizeResponse.IdentityToken`, which is null in the code flow response. Should it be set using `TokenResponse.IdentityToken`?

**Comment by leastprivilege** [comment]
has this been fixed?
