### ISSUE TITLE
LogoutAsyc without IWebView

### ISSUE THREAD

**Issue by mirmajeed1** [DuendeArchive/IdentityModel.OidcClient.Old#23]
I have implemented authentication in Xamarin Form using the WebView control and I have not implemented the IWebView interface. It seems like the LogoutAysnc requires IWebView Interface for it to work. Is there anyway to call logoutAsync without Implementing the IWebView Interface or any other way to implement logout?

**Comment by leastprivilege** [comment]
You can start your own web view pointing to the end session endpoint.

**Comment by leastprivilege** [comment]
btw . there is a new Android sample in the sample repo using the Chrome Custom Tab. That's the recommended way to do login.
