### ISSUE TITLE
Profile must not be loaded if profile scope is requested

### ISSUE THREAD

**Issue by xperiandri** [DuendeArchive/IdentityModel.OidcClient.Old#24]
What is the purpose to send a request to `userinfo` endpoint if `profile` scope is specified?
I think it must check this and does not perform a request in this case.

**Comment by leastprivilege** [comment]
Not sure I understand the question - one is a scope the other a claims delivery mechanism.

**Comment by xperiandri** [comment]
If I request `profile` scope I receive all the profile claims in an identity token.
What is the reason to make unnecessary call to `userinfo` endpoint if all the information already came inside an identity token?

**Comment by leastprivilege** [comment]
The claims are not guaranteed to be in the identity token - depends on configuration (the spec also allows to return only minimal claims in the id_token and use userinfo afterwards). 

If your setup returns all claims in the id_token - then yes - the call to userinfo is not necessary.
