### ISSUE TITLE
Correct way of persisting tokens to disk?

### ISSUE THREAD

**Issue by neoKushan** [DuendeArchive/IdentityModel.OidcClient.Old#28]
Forgive me if I am about to ask a really stupid question, but if I want my application to (Securely) store the result of a login on disk so it can be exited and restarted without forcing the user to log in again (unless tokens have expired), what would be the "correct" way to do this? 

Can I just serialise LoginResult out and in? I suspect this won't work as I don't think HttpMessageHandler will serialise? (Admittedly I have not tried this yet).

Note: I'm not asking about a _secure_ way of storing data on disk, that's not really within the scope of this issue, unless the OidcClient has some built-in method to handle this (That I can't seem to find).

Thanks, I appreciate any help!

**Comment by leastprivilege** [comment]
I would simply persist the refresh token (and maybe access token) along with the claims you want to keep. Use some secure storage API for that (DPAPI, KeyChain etc).

You can then manually create the refresh token handler using a TokenClient instance.

That's something I want to make easier in the future, but for now that's how it works.
