### ISSUE TITLE
PCLCrypto Assembly Exception

### ISSUE THREAD

**Issue by JohBa** [DuendeArchive/IdentityModel.OidcClient.Old#30]
I'm trying to use OidcClient with Xamarin.Forms and manual WebView.
I set the `OidcClientOptions` but with call of `oidcClient.PrepareLoginAsync()` I get the following exception

> PCLCrypto.NotImplementedByReferenceAssemblyException: This is a reference assembly and does not contain implementation. Be sure to install the PCLCrypto package into your application so the platform implementation assembly will be used at runtime.

First time I installed the OidcClient NuGet Package, that also installed the other packages (jose pcl, pclrypto...)
I already uninstalled every NuGet package and reinstalled one by one, unfortunately it didn't help. 
Probably this isn't exactly a bug, but maybe the problem occured already and someone could help me.

**Comment by leastprivilege** [comment]
Please see if you can repro that with the ios sample we provide.

**Comment by leastprivilege** [comment]
any update?

**Comment by JohBa** [comment]
Huge sorry! totally forgot about this, my bad! long time I had no opportunity to test for ios and then i used another package.
