### ISSUE TITLE
Compatibility problems with IdentityModel and OidcClient

### ISSUE THREAD

**Issue by fendres82** [DuendeArchive/IdentityModel.OidcClient.Old#32]
Hi,

the last few days i tried to figure out what the best combination of IdentityModel and OidcClient to use for my WinForms app.

I always stumble across the wrong versions of 'Newtonsoft.Json' package.

**Installed Versions:**
**IdentityModel 1.11.1** (Dep: Newtonsoft.Json greater or equal 8.0.3)
**IdentityModel.OidcClient 1.1.1** (Dep: Newtonsoft.Json greater or equal 8.0.3, IdentityModel greater or equal 1.11.1, PCLCrypto greater or equal 2.0.147)
**Newtonsoft.Json 8.0.3**

After i'm trying to login with
`var result = await _oidcClient.LoginAsync();` 

i get followed exception

`Die Datei oder Assembly "Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)`

Please can you give me an advice which versions to use with the latest OidcClient.

Is there a new OidcClient on the way for IdentityModel 2.0?

special thx

**Comment by leastprivilege** [comment]
does this work for you?

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/WinFormsWebView

**Comment by fendres82** [comment]
The sample on its own is working.

When i try to connect within my app (Versions of IdentityModel.OidcClient and all dependencies are the same like in the working sample) i get the following error:

`Die Datei oder Assembly "Validation, Version=2.2.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)` => Source: PCLCrypto

app.config
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Validation" publicKeyToken="2fc06f0d701809a7" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.3.0.0" newVersion="2.3.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
`

packages.config
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AutoMapper" version="4.1.1" targetFramework="net452" />
  <package id="CommonServiceLocator" version="1.3" targetFramework="net45" />
  <package id="IdentityModel" version="1.12.0" targetFramework="net452" />
  <package id="IdentityModel.OidcClient" version="1.2.1" targetFramework="net452" />
  <package id="jose-pcl" version="0.0.4" targetFramework="net452" />
  <package id="JustMock" version="2016.1.107.7" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net451" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="net45" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
  <package id="PCLCrypto" version="2.0.147" targetFramework="net452" />
  <package id="PInvoke.BCrypt" version="0.3.90" targetFramework="net452" />
  <package id="PInvoke.Kernel32" version="0.3.90" targetFramework="net452" />
  <package id="PInvoke.NCrypt" version="0.3.2" targetFramework="net452" />
  <package id="PInvoke.Windows.Core" version="0.3.90" targetFramework="net452" />
  <package id="System.Net.Http" version="2.0.20126.16343" targetFramework="net452" />
  <package id="System.Net.Http.Formatting.Extension" version="5.2.3.0" targetFramework="net452" />
  <package id="Unity" version="4.0.1" targetFramework="net45" />
  <package id="Validation" version="2.3.7" targetFramework="net452" />
</packages>`

**Comment by leastprivilege** [comment]
Welcome to .NET versioning ;)

Hard to tell what the real problem is - I guess you need to trial and error.

**Comment by fendres82** [comment]
I tried it with the IdentityModel 2.0 RC => it worked, but the IdentityModel was missing something

`IdentityModel.Client.TokenResponse.get_IsHttpError()`

Is this error Client or Model related?

**Comment by leastprivilege** [comment]
IdentityModel v2 is not backwards compatible to v1. You can't use it right now with OidcClient.

What I can do is to update the Json.Net dependency to latest on all v1 projects. That might help you?

**Comment by fendres82** [comment]
Ok, thank you for the news.
Yes that would be great if it's not bothering you, maybe that will fix my problem.

**Comment by leastprivilege** [comment]
OK 

https://www.nuget.org/packages/IdentityModel.OidcClient/1.3.0

should show up soon.

**Comment by fendres82** [comment]
i think i passed the problem with IdentityModel now. i had to go back to 'Validation' version 2.2.8. Thank you so much

now i have the same error with 'jose-pcl'

`Die Datei oder Assembly "Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)`

still got no valid response from LoginAsync()
