### ISSUE TITLE
OidcClient is logging via log4net, how to stop just the OidcClient from logging

### ISSUE THREAD

**Issue by LaurenceSkoropinski** [DuendeArchive/IdentityModel.OidcClient.Old#34]
Have a dll using log4net logging. noticed in the log file that the  OidcClient is logging to this log file. 
Is there any way to stop OidcClient from logging? We need logging for the calling dll but not from the 
OidcClient. 
Messages  logged start...
DEBUG IdentityModel.OidcClient.IdentityTokenValidation.DefaultIdentityTokenValidator - ....

**Comment by LaurenceSkoropinski** [comment]
Placing 
<filter type="log4net.Filter.LoggerMatchFilter">
        <loggerToMatch value="IdentityModel.OidcClient" />
        <acceptOnMatch value="false" />
  </filter>
Into the <appender >< / appender> section of the log4net config file disables them, but a user can change this, so not the ideal solution.

**Comment by LaurenceSkoropinski** [comment]
`<filter type="log4net.Filter.LoggerMatchFilter">
        <loggerToMatch value="IdentityModel.OidcClient" />
        <acceptOnMatch value="false" />
      </filter>`

Into the appender section of the log4net config file disables them, but a user can change this, so not the ideal solution.

**Comment by leastprivilege** [comment]
I added a provider to turn off logging:

https://github.com/IdentityModel/IdentityModel.OidcClient/blob/dev/src/Shared/Infrastructure/NopLogger.cs

It is not released yet - but you can copy it to your project and give it a try

**Comment by leastprivilege** [comment]
Actually  I just pushed 1.4 to nuget which includes that update - so please give it a try ;)
