### ISSUE TITLE
Client is picking the first signature key instead of selecting it by id

### ISSUE THREAD

**Issue by llaurila** [DuendeArchive/IdentityModel.OidcClient.Old#38]
I fixed this issue and attached a diff. Any comments?

[signature-key.diff.txt](https://github.com/IdentityModel/IdentityModel.OidcClient/files/510934/signature-key.diff.txt)

**Comment by llaurila** [comment]
A colleague of mine noticed that this seems to fix issue #12

**Comment by leastprivilege** [comment]
working on it soon

**Comment by leastprivilege** [comment]
done. thanks!
