### ISSUE TITLE
token_endpoint_auth_methods_supported not followed

### ISSUE THREAD

**Issue by llaurila** [DuendeArchive/IdentityModel.OidcClient.Old#39]
Should adhere to token_endpoint_auth_methods_supported as advertised by discovery configuration instead of defaulting to BasicAuth.

I have fixed this issue, here's the diff. Any comments?

[token_endpoint_auth_methods_supported.diff.txt](https://github.com/IdentityModel/IdentityModel.OidcClient/files/510948/token_endpoint_auth_methods_supported.diff.txt)

**Comment by leastprivilege** [comment]
working on it soon

**Comment by leastprivilege** [comment]
I added the parsing of the disco doc manually. Also the authentication method can now be set explicitly. thanks!
