### ISSUE TITLE
InvalidOperationException due to dynamic keyword

### ISSUE THREAD

**Issue by andrew-laughlin** [DuendeArchive/IdentityModel.OidcClient.Old#43]
The following exception occurs when calling PrepareLoginAsync:

```
Exception thrown: 'System.InvalidOperationException' in mscorlib.ni.dll
Additional information: The API 'System.Reflection.MemberInfo.get_MetadataToken()' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information.

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

```

I have a PCL project (Profile7) that references the IdentityModel (1.13.0) and IdentityModel.OidcClient (1.4.0) packages. The PCL is used for common Xamarin forms code. The PCL is referenced by Android, iOS and UWP projects. The Android project runs as expected. The UWP project throws the exception. The exception occurs because the dynamic keyword is used in the logging code. 

Wondering if there is a work-around available?

**Comment by leastprivilege** [comment]
Profile7 does not sound right - I can't remember the exact profile number - but use the same as identitymodel for your shared lib.

**Comment by andrew-laughlin** [comment]
Great suggestion. I set the profile to 259 to match the one used in IdentityModel.OidcClient project, however the exception still occurs.

**Comment by leastprivilege** [comment]
not sure then. Who is using dynamic - can you see that from the exception?

**Comment by andrew-laughlin** [comment]
Dynamic is used in the logging code. The exception occurs here, during instantiation:

`private static dynamic s_currentLogProvider;`

I'm not able to get around this exception, even when synchronizing PCL profiles (Profile 259). As a workaround I've disable the logging and created a custom nuget package we're consuming in our project. I'm not sure how much work it is to refactor the logging to allow ILog to be injected, but that might be a viable solution.

**Comment by andrew-laughlin** [comment]
Upgrading Xamarin for Visual Studio to 4.2.719 resolved the issue
