### ISSUE TITLE
Downloading and uploading files by using OAuth in C# language on the Dropbox Platform without creating a new app on the Dropbox Platform to get applicationkey and secretkey?

### ISSUE THREAD

**Issue by RiyBiy** [DuendeArchive/IdentityModel.OidcClient.Old#54]
Hello,
I use currently the OAuth technique and I have a question and I hope, you can help me?
I would like to know how can I use OAuth 2.0 (within C# WPF application or any langauge to achieve the request the language is not so import) to download and upload files from Dropbox. It appears that the OAuth 2.0 works by forwarding you to a Dropbox Platform and getting you confirm details for example that is means registering the application with external providers(Dropbox Platform API) to get the application key and secret key.
(creating a new application on the Dropbox platform 
to get applicationkey and secret key
https://www.dropbox.com/developers/apps/create.
Is there any way to obtain client id and client secret without creating a new app on the Dropbox API app?)
How can I use it without application key and secret key direct to connect and maybe get the application key with secret key in background without showing anything to the user of the application for example like "Screenpresso" software with this software you don't need to get applciation key or secret key only you sign in by the email and password to grant access the features and dwnload and upload files.
 
If there are other extra techniques, please write them down(if you want to konw more details please install the screenpresso software it is free and you will notice it don't need the applicationkey or secretkey to upload or dwnload files from the dropbox, Drive or OneDrive  etc...).
Thanks in advance.

**Comment by leastprivilege** [comment]
This is the issue tracker of an open source project. You are asking a general question. StackOverflow would be a much better place for that..
