### ISSUE TITLE
Xamarin Android only - Classes in the module cannot be loaded

### ISSUE THREAD

**Issue by voidsstr** [DuendeArchive/IdentityModel.OidcClient.Old#55]
Hello, I'm version 1.7.0 of IdentityModel.OidcClient and receive a class loader exception:

ReflectionTypeLoadException:
The classes in the module cannot be loaded

LoaderExceptions:

Type '__callback_factory__class__' is not finished.

Attached is the exception in Xamarin studio as well as the android build settings I am using.

<img width="979" alt="screen shot 2017-01-05 at 12 36 57 pm" src="https://cloud.githubusercontent.com/assets/11889931/21691028/de53a5b4-d344-11e6-928f-ce1e0858b93c.png">
<img width="891" alt="screen shot 2017-01-05 at 12 36 05 pm" src="https://cloud.githubusercontent.com/assets/11889931/21691032/e245896c-d344-11e6-8963-08298441da2d.png">

**Comment by leastprivilege** [comment]
Do the Android samples work for you?

**Comment by voidsstr** [comment]
The sample loads and the same call (OidcClientOptions constructor) does not throw this exception. However when I click 'Call API', the web page shows 'unauthorized_client' error.

**Comment by leastprivilege** [comment]
Well - that's a different issue.
