### ISSUE TITLE
WinForms client and IdentityServerWithAspNetIdentity

### ISSUE THREAD

**Issue by dpedrelli** [DuendeArchive/IdentityModel.OidcClient.Old#58]
Hi,

I can run the WinForms sample, with the default OidcClientOptions and it works fine.  I installed IdentityServer4.Samples and ran the QuickStart IdentityServerWithAspNetIdentity.  I added IdentityServerConstants.StandardScopes.OpenId to the three, sample clients.  I can call the three different clients from Postman (I had to make all three clients GrantTypes.ResourceOwnerPassword) and they return a valid token.  If I use the exact same parameters for OidcClientOptions, I get "Request validation failed."  How can I use the WinForms sample?  I am attaching two screen captures that show the IdentityServer console outputs.

Thanks
![identityserver4-oidcclient-winforms](https://cloud.githubusercontent.com/assets/17931111/22436785/7ff35ff6-e6f3-11e6-87d7-71bafd9c7406.png)
![identityserver4-postman](https://cloud.githubusercontent.com/assets/17931111/22436787/8253c0a6-e6f3-11e6-9c96-50237eb94fa7.png)

**Comment by dpedrelli** [comment]
The authority in my WinForms client is pointing to HTTP, not HTTPS.  I know that in an MVC or API server client, you can set RequireHttpsMetadata = false.  I do not see a similar setting in IdentityModel.OidcClient.

**Comment by leastprivilege** [comment]
Your first screenshot is not showing the real validation error - you need to scroll up more.

**Comment by dpedrelli** [comment]
That lead me to it.  On the server side, I had to change the client
RedirectUris = { "http://localhost/winforms.client" },
PostLogoutRedirectUris = { "http://localhost/winforms.client" },

Thanks
