### ISSUE TITLE
LoginResult property AccessTokenExpiration DateTime.Now

### ISSUE THREAD

**Issue by initialspark** [DuendeArchive/IdentityModel.OidcClient.Old#61]
Hello,

I was wondering why for the LoginResult in the oidc client the AccessTokenExpiration uses DateTime.Now instead of DateTime.UtcNow? And i guess the same applies to AuthenticationTime.

```
var loginResult = new LoginResult
            {
                Claims = FilterClaims(result.Claims),
                AccessToken = result.TokenResponse.AccessToken,
                RefreshToken = result.TokenResponse.RefreshToken,
                AccessTokenExpiration = DateTime.Now.AddSeconds(result.TokenResponse.ExpiresIn),
                IdentityToken = result.TokenResponse.IdentityToken,
                AuthenticationTime = DateTime.Now
            };`
```
Thanks,

Sandeep

**Comment by leastprivilege** [comment]
Why did you close the issue?

**Comment by initialspark** [comment]
Hi Dom,

I closed it as i read this library is no longer maintained in the readme so i was going to raise the same question in the successor OidcClient2.

Thanks,

Sandeep
