### ISSUE TITLE
Error: No web view configured

### ISSUE THREAD

**Issue by wolfmanfx** [DuendeArchive/IdentityModel.OidcClient.Old#7]
Hi,

I am trying to use this OidcClient within UnitTests. The frontpage says the configuration of an webview is optional but I get the exception "No web view configured".

**Comment by leastprivilege** [comment]
Depends which method you are calling LoginAsync requires the WebView - prepare LoginAsync not.

**Comment by wolfmanfx** [comment]
I doubt thats useful for my case ->
In my unit test the user is generated on the fly (identityserver / MR) than I spawn a second OWIN selfhosted instance which does the API housing (with implcit flow).
Now I want the access_token so I can authitcate against the webapi.

Or do I overlook anything (prepare LoginAsync requires to go into the browser component?)

**Comment by wolfmanfx** [comment]
Got it working with  Flows.HybridWithProofKey.

Thx

**Comment by leastprivilege** [comment]
I don't follow. Check the source code.
